"""add genres to user

Revision ID: 136d2794af3b
Revises: d1e2f3a4b5c6
Create Date: 2026-03-05 15:45:38.192754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '136d2794af3b'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'locked_until')
    op.add_column('version', sa.Column('artifact_path', sa.String(), nullable=True))
    op.add_column('version', sa.Column('artifact_size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('version', sa.Column('artifact_checksum', sa.String(length=128), nullable=True))
    op.add_column('version', sa.Column('source_daw', sa.String(length=50), nullable=True))
    op.add_column('version', sa.Column('source_project_filename', sa.String(length=255), nullable=True))
    op.add_column('version', sa.Column('snapshot_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('version', 'storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('version', 'snapshot_manifest')
    op.drop_column('version', 'source_project_filename')
    op.drop_column('version', 'source_daw')
    op.drop_column('version', 'artifact_checksum')
    op.drop_column('version', 'artifact_size_bytes')
    op.drop_column('version', 'artifact_path')
    op.add_column('users', sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('failed_login_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.VARCHAR(), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'genres')
    # ### end Alembic commands ###
