"""add created_by to version and collaborator created_at

Revision ID: 2b7c42ab9a50
Revises: cb5f23d4c1b9
Create Date: 2026-03-05 12:34:12.129942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b7c42ab9a50'
down_revision: Union[str, None] = 'cb5f23d4c1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('collaborator', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.alter_column('collaborator', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               nullable=False,
               server_default=None)
    op.alter_column('project', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('project', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('project', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('track', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('version', sa.Column('created_by', sa.UUID(), nullable=True))
    op.alter_column('version', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_foreign_key('fk_version_created_by_users_id', 'version', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_version_created_by_users_id', 'version', type_='foreignkey')
    op.alter_column('version', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('version', 'created_by')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('track', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('project', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('project', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('project', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('collaborator', 'created_at')
    op.alter_column('branch', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
