"""Add bio to users

Revision ID: 386961d0f2b6
Revises: 58dbef40b2ff
Create Date: 2026-03-05 10:13:32.481812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '386961d0f2b6'
down_revision: Union[str, None] = '58dbef40b2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('version', sa.Column('storage_path', sa.String(), nullable=True))
    op.drop_column('version', 'snapshot_manifest')
    op.drop_column('version', 'source_daw')
    op.drop_column('version', 'artifact_path')
    op.drop_column('version', 'artifact_size_bytes')
    op.drop_column('version', 'source_project_filename')
    op.drop_column('version', 'artifact_checksum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('artifact_checksum', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('version', sa.Column('source_project_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('version', sa.Column('artifact_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('version', sa.Column('artifact_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('version', sa.Column('source_daw', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('version', sa.Column('snapshot_manifest', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('version', 'storage_path')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'bio')
    op.create_table('token_blacklist',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    # ### end Alembic commands ###
