"""add_soft_delete_columns

Revision ID: 4aad2f560761
Revises: f9161916fc34
Create Date: 2026-03-03 13:34:00.353202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aad2f560761'
down_revision: Union[str, None] = 'f9161916fc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('branch', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_branch_is_deleted'), 'branch', ['is_deleted'], unique=False)
    op.add_column('project', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('project', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_project_is_deleted'), 'project', ['is_deleted'], unique=False)
    op.add_column('version', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('version', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_version_is_deleted'), 'version', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_is_deleted'), table_name='version')
    op.drop_column('version', 'deleted_at')
    op.drop_column('version', 'is_deleted')
    op.drop_index(op.f('ix_project_is_deleted'), table_name='project')
    op.drop_column('project', 'deleted_at')
    op.drop_column('project', 'is_deleted')
    op.drop_index(op.f('ix_branch_is_deleted'), table_name='branch')
    op.drop_column('branch', 'deleted_at')
    op.drop_column('branch', 'is_deleted')
    # ### end Alembic commands ###
