"""add pull_request table

Revision ID: 766188bc9149
Revises: f7d2c1a48901
Create Date: 2026-09-13 15:01:42.033102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '766188bc9149'
down_revision: Union[str, None] = 'f7d2c1a48901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_branch_id', sa.UUID(), nullable=False),
    sa.Column('target_branch_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_head_version_id', sa.UUID(), nullable=True),
    sa.Column('target_head_version_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('OPEN', 'MERGED', 'CLOSED')", name='ck_pull_request_status'),
    sa.CheckConstraint('source_branch_id <> target_branch_id', name='ck_pull_request_distinct_branches'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['source_branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['source_head_version_id'], ['version.id'], ),
    sa.ForeignKeyConstraint(['target_branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['target_head_version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_id'), 'pull_request', ['id'], unique=False)
    op.create_index(op.f('ix_pull_request_is_deleted'), 'pull_request', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pull_request_project_id'), 'pull_request', ['project_id'], unique=False)
    # One OPEN pull request per ordered (source, target) pair; partial so
    # closed/merged/soft-deleted rows never block a new one.
    op.create_index(
        'uq_pull_request_open_pair',
        'pull_request',
        ['source_branch_id', 'target_branch_id'],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN' AND is_deleted = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pull_request_open_pair', table_name='pull_request', postgresql_where=sa.text("status = 'OPEN' AND is_deleted = false"))
    op.drop_index(op.f('ix_pull_request_project_id'), table_name='pull_request')
    op.drop_index(op.f('ix_pull_request_is_deleted'), table_name='pull_request')
    op.drop_index(op.f('ix_pull_request_id'), table_name='pull_request')
    op.drop_table('pull_request')
    # ### end Alembic commands ###
