"""Add attribute is_admin in table USERS

Revision ID: b71f10e958d7
Revises: 13d775b94a79
Create Date: 2026-03-12 13:47:29.891497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b71f10e958d7'
down_revision: Union[str, None] = '13d775b94a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    op.alter_column('collaborator', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    
    if 'users' in tables:
        user_columns = {column['name'] for column in inspector.get_columns('users')}
        if 'is_admin' not in user_columns:
            op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    if 'users' in tables:
        user_columns = {column['name'] for column in inspector.get_columns('users')}
        if 'is_admin' in user_columns:
            op.drop_column('users', 'is_admin')
    
    op.alter_column('collaborator', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
