"""Add nullable created_at to Track

Revision ID: e70ee25e901a
Revises: b41d10f293fb
Create Date: 2026-03-08 20:59:56.583667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70ee25e901a'
down_revision: Union[str, None] = 'b41d10f293fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'created_at')
    # ### end Alembic commands ###
